# Generated by Django 4.2.2 on 2023-06-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spravka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField()),
                ('date', models.DateField()),
                ('grant', models.IntegerField()),
                ('destination', models.TextField()),
            ],
        ),
    ]
