# Generated by Django 4.2.2 on 2023-06-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decanat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spravka',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
