# Generated by Django 4.2.2 on 2023-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decanat', '0002_alter_spravka_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spravka',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spravka',
            name='fio',
            field=models.CharField(max_length=100),
        ),
    ]
