# Generated by Django 4.2.2 on 2023-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decanat', '0003_alter_spravka_destination_alter_spravka_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spravka',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
